Fix asynchronous job
There is another required field in mesos protocbuf message TaskStatus,
without this fix, it will throw an exception when building the protocbuf
message like below:

com.google.protobuf.UninitializedMessageException: Message missing required fields: state
        at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:605)
        at org.apache.mesos.Protos$TaskStatus$Builder.build(Protos.java:18993)
        at com.airbnb.scheduler.api.TaskManagementResource.updateStatus(TaskManagementResource.scala:48)

For the protocbuf message definination, see mesos code:
  include/mesos/mesos.proto

Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>